image: node:latest

stages:
  - installation
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: installation
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
test:
  script:
    - npm run coverage
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
